load(here("functions/data_for_read_and_name_the_data.rda"))

# returns english translation of x; df - data frame that stores translations
ru_to_en <- function(x, df){
  return(df$eng[match(x, df$rus)])
}

# replace regions codes with names
# add_region <- function(.data)
#   {region <- data %>%
#     mutate(region = case_when(region == 10 ~ "Karelia",
#                               region == 11 ~ "Komi",
#                               region == 29 ~ "Arkhangelsk",
#                               region == 35 ~ "Vologda",
#                               region == 39 ~ "Kaliningrad",
#                               region == 47 ~ "Leningrad",
#                               region == 51 ~ "Murmansk",
#                               region == 53 ~ "Novgorod",
#                               region == 60 ~ "Pskov",
#                               region == 78 ~ "Petersburg",
#                               region == 77 ~ "Moscow",
#                               region == 13 ~ "Mordovia",
#                               region == 23 ~ "Krasnodar",
#                               region == 83 ~ "NAO",
#                               region == 33 ~ "Vladimir",
#                               region == 50 ~ "MO",
#                               region == 7  ~ "Kabardino-Balkarian",
#                               region == 31 ~ "Belgorod",
#                               region == 91 ~ "Kaliningrad",
#                               region == 56 ~ "Orenburg",
#                               region == 69 ~ "Tver",
#                               region == 58 ~ "Penza",
#                               region == 76 ~ "Yaroslavl",
#                               region == 24 ~ "Krasnoyarsk",
#                               region == 16 ~ "Tatrstan",
#                               region == 61 ~ "Rostov",
#                               region == 22 ~ "Altai",
#                               region == 86 ~ "Yugra",
#                               region == 25 ~ "Primorye",
#                               region == 67 ~ "Smolensk",
#                               region == 66 ~ "Sverdlovsk",
#                               region == 28 ~ "Amur",
#                               region == 48 ~ "Lipetsk",
#                               region == 2  ~ "Bashkortostan",
#                               region == 92 ~ "Sevastopol",
#                               region == 68 ~ "Tambov",
#                               region == 5  ~ "Daghestan",
#                               region == 37 ~ "Ivanovo",
#                               region == 55 ~ "Omsk",
#                               region == 36 ~ "Voronezh",
#                               region == 74 ~ "Chelyabinsk",
#                               region == 49 ~ "Magadan",
#                               region == 46 ~ "Kursk",
#                               region == 32 ~ "Bryansk",
#                               region == 71 ~ "Tula",
#                               region == 21 ~ "Chuvash Republic",
#                               region == 44 ~ "Kostroma",
#                               region == 27 ~ "Khabarovsk",
#                               region == 26 ~ "Stavropol",
#                               region == 52 ~ "N_Novgorod",
#                               region == 64 ~ "Saratov",
#                               region == 38 ~ "Irkutsk",
#                               region == 57 ~ "Orel",
#                               region == 43 ~ "Kirov",
#                               region == 63 ~ "Samara",
#                               region == 62 ~ "Ryazan",
#                               region == 54 ~ "Novosibirsk",
#                               region == 40 ~ "Kaluga",
#                               region == 99 ~ "Moscow",
#                               region == 75 ~ "Trans-Baikal Territory",
#                               region == 34 ~ "Volgograd",
#                               region == 1  ~ "Adygeya",
#                               region == 30 ~ "Astrakhan",
#                               region == 41 ~ "Kamchatka",
#                               region == 72 ~ "Tyumen",
#                               region == 42 ~ "Kemerovo",
#                               region == 79 ~ "Jewish Autonomous Region",
#                               region == 65 ~ "Sakhalin",
#                               region == 73 ~ "Ulyanovsk",
#                               region == 8  ~ "Kalmykia",
#                               region == 12 ~ "Mari El",
#                               region == 4  ~ "Altai",
#                               region == 70 ~ "Tomsk",
#                               region == 9  ~ "Karachayevo-Circassian Republic",
#                               region == 20 ~ "Chechen Republic",
#                               region == 59 ~ "Perm",
#                               region == 89 ~ "Yamal-Nenets Autonomous Area",
#                               region == 14 ~ "Yakutia",
#                               region == 3  ~ "Buryatia"))
#     
#     return(region)
# }
